apiVersion: v1
kind: Pod
metadata:
  name: employees-pod
  namespace: employees-space
  labels:
    app: employees
spec:
  containers:
  - name: employees
    image: 184549016595.dkr.ecr.us-east-1.amazonaws.com/app:latest
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service.mysql-space.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"
  imagePullSecrets:
    - name: ecr-secret
